// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kerstiyewadsqwkvrafq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlcnN0aXlld2Fkc3F3a3ZyYWZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MjgxNDksImV4cCI6MjA3MzUwNDE0OX0.A7r5gtYbJfRaAZlubv8ivUq1R2262PaRED9DnJVhgH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});